"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { cleanQuestionStem } from "@/lib/question-text";

type Item = { id: string; stem: string; selected_key: string; review_count: number; status: string };
type CourseUsage = { course: string; answers_count: number; total_seconds: number };
type ActivityUser = { id: number; username: string; email: string; identity_type: "registered" | "guest"; role: string; last_active_at: string; questions_answered: number; sessions_count: number; total_seconds: number; courses: CourseUsage[] };
type Report = { id: number; question_id: number; category: string; details: string | null; reporter: string; created_at: string; stem: string; options: { key: string; text: string }[]; material_supported_key: string; explanation: string | null; course: string };
type BankQuestion = { id: number; course: string; stem: string; options: { key: string; text: string }[]; material_supported_key: string | null; explanation: string | null; verification_status: string; display_name: string | null };
type AdminUser = { id: number; username: string; email: string; last_seen_at: string };

const courseNames: Record<string, string> = { civil_litigation: "Civil", criminal_litigation: "Criminal", corporate_law_practice: "Corporate", property_law_practice: "Property", professional_ethics_skills: "Ethics" };
function timeLabel(seconds: number) { if (!seconds) return "0m"; const hours = Math.floor(seconds / 3600); const minutes = Math.round(seconds % 3600 / 60); return hours ? `${hours}h ${minutes}m` : `${minutes}m`; }

export default function AdminPage() {
  const [tab, setTab] = useState<"users" | "questions" | "reports" | "experts" | "team">("users"); const [email, setEmail] = useState(""); const [adminEmail, setAdminEmail] = useState(""); const [admins, setAdmins] = useState<AdminUser[]>([]); const [invite, setInvite] = useState(""); const [items, setItems] = useState<Item[]>([]); const [users, setUsers] = useState<ActivityUser[]>([]); const [reports, setReports] = useState<Report[]>([]); const [editing, setEditing] = useState<Report | null>(null); const [bankEditing, setBankEditing] = useState<BankQuestion | null>(null); const [editStem, setEditStem] = useState(""); const [editOptions, setEditOptions] = useState<{ key: string; text: string }[]>([]); const [editAnswer, setEditAnswer] = useState(""); const [editExplanation, setEditExplanation] = useState(""); const [bankQuestions, setBankQuestions] = useState<BankQuestion[]>([]); const [bankSearch, setBankSearch] = useState(""); const [bankCourse, setBankCourse] = useState(""); const [bankStatus, setBankStatus] = useState(""); const [bankPage, setBankPage] = useState(1); const [bankTotal, setBankTotal] = useState(0); const [bankMore, setBankMore] = useState(false); const [msg, setMsg] = useState("");
  async function load() {
    const [consensus, activity, reportResponse, adminResponse] = await Promise.all([fetch("/api/admin/consensus"), fetch("/api/admin/activity"), fetch("/api/admin/question-reports"), fetch("/api/admin/admins")]);
    const [consensusData, activityData, reportData, adminData] = await Promise.all([consensus.json(), activity.json(), reportResponse.json(), adminResponse.json()]);
    setItems(consensusData.items ?? []); setUsers(activityData.users ?? []); setReports(reportData.reports ?? []); setAdmins(adminData.admins ?? []);
  }
  useEffect(() => { void load(); }, []);
  async function makeInvite() { const response = await fetch("/api/admin/invites", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ email }) }); const data = await response.json(); setInvite(data.inviteUrl ?? data.error ?? ""); }
  async function act(id: string, action: "approve" | "reject") { await fetch("/api/admin/consensus", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ questionId: id, action }) }); setMsg("Decision saved."); void load(); }
  function beginEdit(report: Report) { setEditing(report); setEditStem(report.stem); setEditOptions(report.options); setEditAnswer(report.material_supported_key); setEditExplanation(report.explanation ?? ""); }
  async function resolveReport(action: "save" | "dismiss") { if (!editing) return; const response = await fetch("/api/admin/question-reports", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ reportId: editing.id, action, stem: editStem, options: editOptions, answerKey: editAnswer, explanation: editExplanation }) }); const data = await response.json(); setMsg(response.ok ? (action === "save" ? "Correction published live and report resolved." : "Report dismissed.") : (data.error ?? "Could not update report.")); if (response.ok) { setEditing(null); void load(); } }
  async function loadBank(page = bankPage) { const params = new URLSearchParams({ page: String(page) }); if (bankSearch.trim()) params.set("search", bankSearch.trim()); if (bankCourse) params.set("course", bankCourse); if (bankStatus) params.set("status", bankStatus); const response = await fetch(`/api/admin/questions?${params}`); const data = await response.json(); setBankQuestions(data.questions ?? []); setBankTotal(data.total ?? 0); setBankMore(Boolean(data.hasMore)); setBankPage(page); }
  function beginBankEdit(question: BankQuestion) { setBankEditing(question); setEditing(null); setEditStem(question.stem); setEditOptions(question.options); setEditAnswer(question.material_supported_key ?? question.options[0]?.key ?? ""); setEditExplanation(question.explanation ?? ""); window.setTimeout(() => document.getElementById("bank-question-editor")?.scrollIntoView({ behavior: "smooth", block: "start" }), 0); }
  async function publishBank() { if (!bankEditing) return; const response = await fetch("/api/admin/questions", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ questionId: bankEditing.id, stem: editStem, options: editOptions, answerKey: editAnswer, explanation: editExplanation }) }); const data = await response.json(); setMsg(response.ok ? "Correction published live." : (data.error ?? "Could not publish correction.")); if (response.ok) { setBankEditing(null); void loadBank(); } }
  async function changeBankStatus(action: "unpublish" | "delete") { if (!bankEditing) return; const prompt = action === "delete" ? "Delete this question permanently? Its related attempts, reports, and reviews will also be removed." : "Unpublish this question? Students will no longer see it, but you can review and publish it again later."; if (!window.confirm(prompt)) return; const response = await fetch("/api/admin/questions", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ questionId: bankEditing.id, action }) }); const data = await response.json(); setMsg(response.ok ? (action === "delete" ? "Question deleted permanently." : "Question unpublished. It is no longer visible to students.") : (data.error ?? "Could not update this question.")); if (response.ok) { setBankEditing(null); void loadBank(); } }
  async function addAdmin() { const response = await fetch("/api/admin/admins", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ email: adminEmail }) }); const data = await response.json(); setMsg(response.ok ? `${adminEmail.trim()} now has admin access.` : (data.error ?? "Could not add admin.")); if (response.ok) { setAdminEmail(""); void load(); } }
  return <main><Link className="back-link" href="/">← Home</Link><p className="eyebrow">Admin</p><h1>Manage the tool.</h1>
    <nav className="admin-tabs" aria-label="Admin sections"><button className={tab === "users" ? "active" : ""} type="button" onClick={() => setTab("users")}>Users</button><button className={tab === "questions" ? "active" : ""} type="button" onClick={() => { setTab("questions"); void loadBank(1); }}>Questions</button><button className={tab === "reports" ? "active" : ""} type="button" onClick={() => setTab("reports")}>Reports</button><button className={tab === "experts" ? "active" : ""} type="button" onClick={() => setTab("experts")}>Experts</button><button className={tab === "team" ? "active" : ""} type="button" onClick={() => setTab("team")}>Team</button></nav>
    {tab === "users" && <>
    <section className="panel admin-activity"><p className="eyebrow">User activity</p><h2>Students using the tool.</h2><p className="muted">{users.length} profile{users.length === 1 ? "" : "s"} · question and time totals update after each answer.</p>
      <div className="activity-list">{users.map((user) => <article className="activity-row" key={user.id}><div className="activity-person"><strong>{user.username}</strong><span>{user.identity_type === "guest" ? "Guest session" : user.email} · {user.role}</span><small>Last active {new Date(user.last_active_at).toLocaleString()}</small></div><div className="activity-stat"><strong>{user.questions_answered}</strong><span>answers</span></div><div className="activity-stat"><strong>{timeLabel(user.total_seconds)}</strong><span>studied</span></div><div className="activity-courses">{user.courses.length ? user.courses.map((course) => <span key={course.course}>{courseNames[course.course] ?? course.course}: {course.answers_count} · {timeLabel(course.total_seconds)}</span>) : <span>No course activity yet</span>}</div></article>)}</div>
    </section></>}
    {tab === "questions" && <>
    <section className="panel question-bank"><p className="eyebrow">Question bank</p><h2>Review every question.</h2><p className="muted">Select a row to see its options and review it before publishing.</p><div className="bank-controls"><input value={bankSearch} onChange={(event) => setBankSearch(event.target.value)} placeholder="Search question text" /><select value={bankCourse} onChange={(event) => setBankCourse(event.target.value)}><option value="">All courses</option><option value="civil_litigation">Civil Litigation</option><option value="criminal_litigation">Criminal Litigation</option><option value="corporate_law_practice">Corporate Law Practice</option><option value="property_law_practice">Property Law Practice</option><option value="professional_ethics_skills">Professional Ethics &amp; Skills</option><option value="general">General</option></select><select value={bankStatus} onChange={(event) => setBankStatus(event.target.value)}><option value="">All live statuses</option><option value="live">Live</option><option value="not_live">Not live</option><option value="unreviewed">Unreviewed</option><option value="insufficient_material">Insufficient material</option><option value="material_conflicted">Conflicted</option></select><button className="outline-button" type="button" onClick={() => { void loadBank(1); }}>Search</button></div><p className="muted">{bankTotal ? `${bankTotal.toLocaleString()} matching questions` : "Opening question bank…"}</p>{bankQuestions.length > 0 && <div className="review-list">{bankQuestions.map((question) => <article className="review-row question-bank-row" key={question.id} onClick={() => beginBankEdit(question)}><p className="eyebrow">#{question.id} · {question.course} · {question.verification_status}</p><p>{cleanQuestionStem(question.stem)}</p></article>)}</div>}{bankQuestions.length > 0 && <div className="button-row question-bank-pages"><button className="secondary" type="button" disabled={bankPage === 1} onClick={() => { void loadBank(bankPage - 1); }}>Previous</button><span>Page {bankPage}</span><button className="secondary" type="button" disabled={!bankMore} onClick={() => { void loadBank(bankPage + 1); }}>Next</button></div>}</section>
    {bankEditing && <section id="bank-question-editor" className="panel report-editor"><p className="eyebrow">Reviewing question #{bankEditing.id}</p><label>Question wording</label><textarea value={editStem} onChange={(event) => setEditStem(event.target.value)} />{editOptions.map((option, index) => <div className="option-edit" key={option.key}><strong>{option.key}</strong><input value={option.text} onChange={(event) => setEditOptions((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, text: event.target.value } : item))} /></div>)}<label>Correct answer</label><select value={editAnswer} onChange={(event) => setEditAnswer(event.target.value)}>{editOptions.map((option) => <option key={option.key} value={option.key}>{option.key} — {option.text}</option>)}</select><label>Explanation</label><textarea value={editExplanation} onChange={(event) => setEditExplanation(event.target.value)} /><div className="button-row"><button className="primary-button" type="button" onClick={() => { void publishBank(); }}>Publish correction</button><button className="secondary" type="button" onClick={() => { void changeBankStatus("unpublish"); }}>Unpublish</button><button className="danger-button" type="button" onClick={() => { void changeBankStatus("delete"); }}>Delete permanently</button><button className="text-button" type="button" onClick={() => setBankEditing(null)}>Cancel</button></div></section>}
    </>}{tab === "reports" && <><section className="panel report-queue"><p className="eyebrow">Question reports</p><h2>Fix reported questions.</h2>{!reports.length ? <p className="muted">No question reports awaiting review.</p> : <div className="review-list">{reports.map((report) => <article className="review-row" key={report.id}><p className="eyebrow">{report.category} · reported by {report.reporter}</p><p>{report.stem}</p>{report.details && <p className="saved-note">{report.details}</p>}<button type="button" className="outline-button" onClick={() => beginEdit(report)}>Edit &amp; resolve</button></article>)}</div>}</section>
    {editing && <section className="panel report-editor"><p className="eyebrow">Editing reported question</p><label>Question wording</label><textarea value={editStem} onChange={(event) => setEditStem(event.target.value)} />{editOptions.map((option, index) => <div className="option-edit" key={option.key}><strong>{option.key}</strong><input value={option.text} onChange={(event) => setEditOptions((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, text: event.target.value } : item))} /></div>)}<label>Correct answer</label><select value={editAnswer} onChange={(event) => setEditAnswer(event.target.value)}>{editOptions.map((option) => <option key={option.key} value={option.key}>{option.key} — {option.text}</option>)}</select><label>Explanation</label><textarea value={editExplanation} onChange={(event) => setEditExplanation(event.target.value)} /><div className="button-row"><button className="primary-button" type="button" onClick={() => { void resolveReport("save"); }}>Publish correction</button><button className="secondary" type="button" onClick={() => { void resolveReport("dismiss"); }}>Dismiss report</button><button className="text-button" type="button" onClick={() => setEditing(null)}>Cancel</button></div></section>}
    </>}{tab === "experts" && <><div className="expert-workspace"><section className="panel compact-panel"><p className="eyebrow">Experts</p><h2>Invite an expert.</h2><p className="muted">They can independently review questions that need a second opinion.</p><div className="invite-controls"><input type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="expert@example.com" /><button className="primary-button" type="button" onClick={() => { void makeInvite(); }}>Create invite</button></div>{invite && <p className="source">Share this one-time link: {invite}</p>}</section>
    <section className="panel compact-panel review-queue"><p className="eyebrow">Expert reviews</p><h2>Review queue.</h2>{items.map((item) => <div key={item.id} className="review-row"><div className="review-row-top"><p>{cleanQuestionStem(item.stem)}</p>{item.status === "awaiting_reviews" && !item.selected_key && <Link className="outline-button" href={`/expert?question=${item.id}`}>Review answer</Link>}</div><p className="source">{item.review_count} review{item.review_count === 1 ? "" : "s"} · proposed {item.selected_key ?? "answer not selected"}</p>{item.selected_key && <div className="button-row"><button type="button" onClick={() => { void act(item.id, "approve"); }}>Approve review</button><button className="secondary" type="button" onClick={() => { void act(item.id, "reject"); }}>Reject</button></div>}</div>)}{!items.length && <p className="muted">No reviews awaiting action.</p>}</section></div>
    </>}{tab === "team" && <section className="panel admin-access"><p className="eyebrow">Team</p><h2>Administrators.</h2><p className="muted">Admins can manage users, experts, reports, and the question bank.</p><div className="bank-controls"><input type="email" value={adminEmail} onChange={(event) => setAdminEmail(event.target.value)} placeholder="admin@example.com" /><button className="primary-button" type="button" onClick={() => { void addAdmin(); }}>Add new admin</button></div>{admins.length ? <div className="activity-list">{admins.map((admin) => <article className="activity-row" key={admin.id}><div className="activity-person"><strong>{admin.username}</strong><span>{admin.email}</span></div><div className="activity-stat"><strong>Admin</strong><span>access level</span></div></article>)}</div> : <p className="muted">No administrators found.</p>}</section>}{msg && <p role="status">{msg}</p>}</main>;
}
