"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";

const courses = [
  ["civil_litigation", "Civil Litigation"], ["criminal_litigation", "Criminal Litigation"],
  ["corporate_law_practice", "Corporate Law Practice"], ["property_law_practice", "Property Law Practice"],
  ["professional_ethics_skills", "Professional Ethics & Skills"],
];

export default function SprintSetup() {
  const router = useRouter(); const [minutes, setMinutes] = useState(0); const [count, setCount] = useState(0); const [selected, setSelected] = useState<string[]>([]); const [timeEdited, setTimeEdited] = useState(false); const [countEdited, setCountEdited] = useState(false); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [showSetup, setShowSetup] = useState(false); const [history, setHistory] = useState<{ id: number; question_count: number; duration_seconds: number; started_at: string; completed_at: string | null; status: string; correct_count: number }[] | null>(null);
  useEffect(() => { void fetch("/api/sprints?history=1").then((response) => response.json()).then((data) => setHistory(data.sprints ?? [])).catch(() => setHistory([])); }, []);
  function updateCourses(next: string[]) { setSelected(next); if (!timeEdited) setMinutes(next.length * 12); if (!countEdited) setCount(next.length * 20); }
  function toggle(course: string) { updateCourses(selected.includes(course) ? selected.filter((item) => item !== course) : [...selected, course]); }
  function adjust(field: "minutes" | "count", amount: number) { if (field === "minutes") { setTimeEdited(true); setMinutes((value) => Math.max(1, Math.min(180, value + amount))); } else { setCountEdited(true); setCount((value) => Math.max(1, Math.min(100, value + amount))); } }
  async function start() { setBusy(true); setError(""); const response = await fetch("/api/sprints", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "create", courses: selected, count, minutes }) }); const data = await response.json(); setBusy(false); if (!response.ok) { setError(data.error ?? "Could not create this sprint."); return; } router.push(`/sprint/${data.sprintId}`); }
  if (!showSetup) return <main className="narrow"><Link className="back-link" href="/">← Back to home</Link><p className="eyebrow">Test sprints</p><h1>Practice under time.</h1><p className="lead">Build a short, focused exam and review your completed sprints here.</p><button className="primary-button" type="button" onClick={() => setShowSetup(true)}>Start new sprint</button><section className="sprint-history"><p className="eyebrow">Past sprints</p>{history === null ? <p className="muted">Loading your sprint history…</p> : !history.length ? <section className="panel empty-state"><h2>No sprints yet.</h2><p className="muted">Start one when you want a focused timed test.</p></section> : <div className="session-list">{history.map((sprint) => { const score = Math.round(sprint.correct_count / sprint.question_count * 100); return <Link className="card session-row" key={sprint.id} href={`/sprint/${sprint.id}`}><div><p className="eyebrow">{new Date(sprint.completed_at ?? sprint.started_at).toLocaleDateString(undefined, { day: "numeric", month: "short", year: "numeric" })} · {sprint.status === "timed_out" ? "Timed out" : "Completed"}</p><h2>{sprint.question_count} question sprint</h2><p className="muted">{Math.round(sprint.duration_seconds / 60)} minutes allowed</p></div><div className="session-score"><strong>{score}%</strong><span>{sprint.correct_count}/{sprint.question_count} correct</span></div></Link>; })}</div>}</section></main>;
  return <main className="narrow"><Link className="back-link" href="/sprint">← Sprint history</Link><p className="eyebrow">Test sprint</p><h1>Design a focused run.</h1><p className="lead">Your answers stay hidden until the sprint is complete, just like an exam.</p><section className="panel sprint-setup"><h2>Time</h2><div className="number-stepper"><button type="button" aria-label="Reduce time" onClick={() => adjust("minutes", -1)}>−</button><input aria-label="Sprint duration in minutes" type="number" min="1" max="180" value={minutes} onChange={(event) => { setTimeEdited(true); setMinutes(Math.max(0, Math.min(180, Number(event.target.value)))); }} /><span>minutes</span><button type="button" aria-label="Increase time" onClick={() => adjust("minutes", 1)}>+</button></div><p className="hint">The default is 12 minutes for each selected course.</p><h2>Questions</h2><div className="number-stepper"><button type="button" aria-label="Reduce question count" onClick={() => adjust("count", -1)}>−</button><input aria-label="Number of questions" type="number" min="1" max="100" value={count} onChange={(event) => { setCountEdited(true); setCount(Math.max(0, Math.min(100, Number(event.target.value)))); }} /><span>questions</span><button type="button" aria-label="Increase question count" onClick={() => adjust("count", 1)}>+</button></div><p className="hint">The default is 20 questions for each selected course.</p><div className="course-checklist-heading"><h2>Courses</h2><button type="button" className="text-button" onClick={() => updateCourses(selected.length === courses.length ? [] : courses.map(([id]) => id))}>{selected.length === courses.length ? "Clear all" : "Select all"}</button></div><div className="course-checklist">{courses.map(([id,label]) => <label key={id} className="course-check"><input type="checkbox" checked={selected.includes(id)} onChange={() => toggle(id)} /><span>{label}</span></label>)}</div><p className="sprint-summary">{count ? Math.floor((minutes * 60) / count) : 0} seconds per question · {selected.length} course{selected.length === 1 ? "" : "s"} selected</p>{error && <p className="error">{error}</p>}<button className="primary-button" disabled={busy || !selected.length || !minutes || !count} onClick={() => { void start(); }}>{busy ? "Building sprint…" : "Start sprint"}</button></section></main>;
}
