"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { useCallback, useEffect, useMemo, useState } from "react";
import { cleanQuestionStem } from "@/lib/question-text";
import { QuestionReport } from "@/components/question-report";
import { CaseStudy } from "@/components/case-study";

type Item = { position: number; question_id: number; chosen_key: string | null; is_correct: boolean | null; seconds_spent: number; course: string; stem: string; options: { key: string; text: string }[]; material_supported_key: string | null; explanation: string | null; shared_context: string | null; context_group_id: string | null; context_position: number | null; finished: boolean };
type Sprint = { id: number; question_count: number; duration_seconds: number; started_at: string; completed_at: string | null; status: string };
type SprintData = { sprint: Sprint; items: Item[] };
function format(seconds: number) { return `${String(Math.floor(seconds / 60)).padStart(2, "0")}:${String(seconds % 60).padStart(2, "0")}`; }

export default function SprintRun() {
  const params = useParams<{ id: string }>(); const id = Number(params.id); const [data, setData] = useState<SprintData | null>(null); const [error, setError] = useState(""); const [activeIndex, setActiveIndex] = useState(0); const [picked, setPicked] = useState(""); const [remaining, setRemaining] = useState(0); const [itemStartedAt, setItemStartedAt] = useState(Date.now()); const [introducedScenarios, setIntroducedScenarios] = useState<Set<string>>(new Set()); const [showCaseStudy, setShowCaseStudy] = useState(false);
  const load = useCallback(async () => { const response = await fetch(`/api/sprints?id=${id}`); const payload = await response.json(); if (!response.ok) { setError(payload.error ?? "Could not load sprint."); return; } setRemaining(Math.max(0, payload.sprint.duration_seconds - Math.floor((Date.now() - new Date(payload.sprint.started_at).getTime()) / 1000))); setData(payload); const first = payload.items.findIndex((item: Item) => !item.chosen_key); setActiveIndex(first === -1 ? 0 : first); setPicked(""); setItemStartedAt(Date.now()); }, [id]);
  useEffect(() => { if (Number.isSafeInteger(id)) void load(); }, [id, load]);
  const elapsed = data ? Math.floor((Date.now() - new Date(data.sprint.started_at).getTime()) / 1000) : 0;
  useEffect(() => { if (!data || data.sprint.status !== "active") return; const update = () => setRemaining(Math.max(0, data.sprint.duration_seconds - Math.floor((Date.now() - new Date(data.sprint.started_at).getTime()) / 1000))); update(); const timer = window.setInterval(update, 1000); return () => window.clearInterval(timer); }, [data]);
  const finish = useCallback(async (timedOut = false) => { if (!data || data.sprint.status !== "active") return; await fetch("/api/sprints", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "finish", sprintId: data.sprint.id, timedOut }) }); void load(); }, [data, load]);
  async function endSprint() { if (!window.confirm("End this sprint now? Any unanswered questions will be marked incorrect.")) return; await finish(false); }
  useEffect(() => { if (data?.sprint.status === "active" && remaining === 0 && elapsed >= data.sprint.duration_seconds) void finish(true); }, [data?.sprint.duration_seconds, data?.sprint.status, elapsed, finish, remaining]);
  const current = data?.items[activeIndex];
  async function submit() { if (!data || !current || !picked) return; const secondsSpent = Math.max(1, Math.round((Date.now() - itemStartedAt) / 1000)); const response = await fetch("/api/sprints", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "answer", sprintId: data.sprint.id, questionId: current.question_id, chosenKey: picked, secondsSpent }) }); if (!response.ok) { const responseData = await response.json(); setError(responseData.error ?? "Could not save your answer."); return; } const nextIndex = activeIndex + 1; if (nextIndex >= data.items.length) { await finish(false); } else { setData({ ...data, items: data.items.map((item, index) => index === activeIndex ? { ...item, chosen_key: picked } : item) }); setActiveIndex(nextIndex); setPicked(""); setShowCaseStudy(false); setItemStartedAt(Date.now()); } }
  async function skipQuestion() { if (!data) return; const nextIndex = activeIndex + 1; if (nextIndex >= data.items.length) { await finish(false); return; } setActiveIndex(nextIndex); setPicked(""); setShowCaseStudy(false); setItemStartedAt(Date.now()); }
  const score = useMemo(() => data?.items.filter((item) => item.is_correct).length ?? 0, [data]);
  if (error && !data) return <main className="narrow"><Link className="back-link" href="/sprint">← Back to sprints</Link><p className="error">{error}</p></main>;
  if (!data) return <main className="narrow"><p className="muted">Preparing your sprint…</p></main>;
  const finished = data.sprint.status !== "active";
  if (finished) return <main className="narrow"><Link className="back-link" href="/sprint">← Design another sprint</Link><p className="eyebrow">Sprint complete</p><h1>{score} / {data.items.length}</h1><p className="lead">{data.sprint.status === "timed_out" ? "Time ran out. Unanswered questions are marked incorrect." : score / data.items.length >= .7 ? "Strong work — review the misses while they are fresh." : "Review each answer, then target the rules that slowed you down."}</p><section className="panel sprint-results"><p className="sprint-summary">{format(Math.min(data.sprint.duration_seconds, Math.floor((new Date(data.sprint.completed_at ?? Date.now()).getTime() - new Date(data.sprint.started_at).getTime()) / 1000)))} used · {Math.round(score / data.items.length * 100)}% accurate</p>{data.items.map((item) => <article key={item.question_id} className={`sprint-review ${item.is_correct ? "correct" : "incorrect"}`}><p className="eyebrow">{item.is_correct ? "✓ Correct" : `✕ Answer: ${item.material_supported_key} — ${item.options.find((option) => option.key === item.material_supported_key)?.text ?? ""}`}</p><h2>{cleanQuestionStem(item.stem)}</h2><p>{item.explanation?.replace(/^(The materials (expressly )?(state|say) that|According to the materials,?\s*)/i, "") ?? "Tutor explanation pending."}</p></article>)}</section><div className="button-row"><Link className="button-link" href="/sprint">Another sprint</Link><Link className="secondary button-link-muted" href="/progress">See progress</Link></div></main>;
  if (!current) return <main className="narrow"><p className="muted">Preparing your next question…</p></main>;
  const scenarioNeedsIntroduction = Boolean(current.context_group_id && current.shared_context && !introducedScenarios.has(current.context_group_id));
  if (scenarioNeedsIntroduction) return <main className="narrow"><button className="back-link sprint-end-button" type="button" onClick={() => { void endSprint(); }}>End sprint</button><div className="sprint-top"><p className="eyebrow">Timed sprint · Case study</p><strong className={remaining < 120 ? "sprint-clock urgent" : "sprint-clock"}>{format(remaining)}</strong></div><section className="panel case-study-intro"><p className="eyebrow">Read this first</p><h1>Case study</h1><CaseStudy text={current.shared_context as string} /><button className="primary-button" type="button" onClick={() => { setIntroducedScenarios((groups) => new Set(groups).add(current.context_group_id as string)); }}>Continue to question {activeIndex + 1}</button></section></main>;
  return <main className="narrow"><button className="back-link sprint-end-button" type="button" onClick={() => { void endSprint(); }}>End sprint</button><div className="sprint-top"><p className="eyebrow">Timed sprint · Question {activeIndex + 1} of {data.items.length}</p><strong className={remaining < 120 ? "sprint-clock urgent" : "sprint-clock"}>{format(remaining)}</strong></div><div className="practice-progress"><span style={{ width: `${(activeIndex / data.items.length) * 100}%` }} /></div><section className="panel question-panel"><p className="question-meta">{current.course}</p>{current.shared_context && <button className="case-study-link" type="button" onClick={() => setShowCaseStudy(true)}>See case study</button>}{showCaseStudy && current.shared_context && <CaseStudy text={current.shared_context} modal onClose={() => setShowCaseStudy(false)} />}<p className="stem">{cleanQuestionStem(current.stem)}</p><div className="options">{current.options.map((option) => <label key={option.key} className={`option ${picked === option.key ? "selected" : ""}`}><input type="radio" name="answer" checked={picked === option.key} onChange={() => setPicked(option.key)} /><strong>{option.key}</strong><span>{option.text}</span></label>)}</div><QuestionReport questionId={current.question_id} />{error && <p className="error">{error}</p>}<div className="button-row practice-actions"><button className="primary-button" disabled={!picked} onClick={() => { void submit(); }}>{activeIndex + 1 === data.items.length ? "Finish sprint" : "Next question"}</button><button className="outline-button" type="button" onClick={() => { void skipQuestion(); }}>{activeIndex + 1 === data.items.length ? "Skip and finish" : "Skip question"}</button></div></section></main>;
}
