"use client";
import Link from "next/link";
import { useEffect, useState } from "react";

type Question = { id: string; stem: string; options: { key: string; text: string }[]; course: string | null; source_name: string | null; source_locator: string | null; consensus_status: string };
export default function ExpertPage() {
  const [items,setItems]=useState<Question[]>([]); const [active,setActive]=useState<Question|null>(null); const [key,setKey]=useState(""); const [explanation,setExplanation]=useState(""); const [citations,setCitations]=useState(""); const [confidence,setConfidence]=useState("medium"); const [message,setMessage]=useState("");
  useEffect(()=>{fetch("/api/expert/reviews").then(r=>r.json()).then(d=>{setItems(d.questions??[]);setActive(d.questions?.[0]??null);}).catch(()=>setMessage("Could not load the expert queue."));},[]);
  async function submit(){ if(!active)return; const r=await fetch("/api/expert/reviews",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({questionId:active.id,selectedKey:key,explanation,citations:citations.split("\n").map(x=>x.trim()).filter(Boolean),confidence})}); const d=await r.json(); if(!r.ok){setMessage(d.error??"Could not save review.");return;} setMessage("Review saved. It remains independent until another expert submits."); setItems(items.filter(x=>x.id!==active.id)); setActive(items.find(x=>x.id!==active.id)??null);setKey("");setExplanation("");setCitations("");}
  return <main><Link className="back-link" href="/">← Home</Link><p className="eyebrow">Expert review</p><h1>Resolve open questions.</h1>{!active?<p>{message||"No open questions right now."}</p>:<section className="panel"><p className="question-meta">{active.course??"Course not identified"} · {active.consensus_status.replaceAll("_"," ")}</p><p className="stem">{active.stem}</p>{active.options.map(o=><label key={o.key} className={`option ${key===o.key?"selected":""}`}><input type="radio" name="answer" checked={key===o.key} onChange={()=>setKey(o.key)}/><strong>{o.key}</strong><span>{o.text}</span></label>)}<label>Reasoning</label><textarea value={explanation} onChange={e=>setExplanation(e.target.value)} placeholder="Why does the evidence support this option?"/><label>Supporting citations (one per line)</label><textarea value={citations} onChange={e=>setCitations(e.target.value)} placeholder="Document, page or section"/><label>Confidence</label><select value={confidence} onChange={e=>setConfidence(e.target.value)}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select><button type="button" disabled={!key||!explanation||!citations} onClick={()=>void submit()}>Submit independent review</button><p className="source">Original source: {active.source_name}{active.source_locator?` · ${active.source_locator}`:""}</p></section>} {message&&<p role="status">{message}</p>}</main>;
}
